
package Biling1;


public class BillingSystem1 extends javax.swing.JFrame {
String operations ;
String answers;
double firstnum,secondnum,result;
    public BillingSystem1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BDisplay1 = new javax.swing.JTextField();
        bdiv1 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        badd1 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        bm1 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        bmul1 = new javax.swing.JButton();
        bans1 = new javax.swing.JButton();
        bdot1 = new javax.swing.JButton();
        bmod1 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        bclear1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(330, 360));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 360));
        jPanel1.setLayout(null);

        BDisplay1.setEditable(false);
        BDisplay1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDisplay1ActionPerformed(evt);
            }
        });
        jPanel1.add(BDisplay1);
        BDisplay1.setBounds(30, 20, 270, 50);

        bdiv1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bdiv1.setText("/");
        bdiv1.setPreferredSize(new java.awt.Dimension(60, 50));
        bdiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdiv1ActionPerformed(evt);
            }
        });
        jPanel1.add(bdiv1);
        bdiv1.setBounds(240, 260, 60, 50);

        b10.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b10.setText("7");
        b10.setPreferredSize(new java.awt.Dimension(60, 50));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel1.add(b10);
        b10.setBounds(30, 80, 60, 50);

        b11.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b11.setText("8");
        b11.setPreferredSize(new java.awt.Dimension(60, 50));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel1.add(b11);
        b11.setBounds(100, 80, 60, 50);

        b12.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b12.setText("9");
        b12.setPreferredSize(new java.awt.Dimension(60, 50));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel1.add(b12);
        b12.setBounds(170, 80, 60, 50);

        badd1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        badd1.setText("+");
        badd1.setPreferredSize(new java.awt.Dimension(60, 50));
        badd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badd1ActionPerformed(evt);
            }
        });
        jPanel1.add(badd1);
        badd1.setBounds(240, 80, 60, 50);

        b13.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b13.setText("4");
        b13.setPreferredSize(new java.awt.Dimension(60, 50));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        jPanel1.add(b13);
        b13.setBounds(30, 140, 60, 50);

        b14.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b14.setText("5");
        b14.setPreferredSize(new java.awt.Dimension(60, 50));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        jPanel1.add(b14);
        b14.setBounds(100, 140, 60, 50);

        b15.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b15.setText("6");
        b15.setPreferredSize(new java.awt.Dimension(60, 50));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        jPanel1.add(b15);
        b15.setBounds(170, 140, 60, 50);

        bm1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bm1.setText("-");
        bm1.setPreferredSize(new java.awt.Dimension(60, 50));
        bm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bm1ActionPerformed(evt);
            }
        });
        jPanel1.add(bm1);
        bm1.setBounds(240, 140, 60, 50);

        b16.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b16.setText("1");
        b16.setPreferredSize(new java.awt.Dimension(60, 50));
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        jPanel1.add(b16);
        b16.setBounds(30, 200, 60, 50);

        b17.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b17.setText("2");
        b17.setPreferredSize(new java.awt.Dimension(60, 50));
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        jPanel1.add(b17);
        b17.setBounds(100, 200, 60, 50);

        b18.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b18.setText("3");
        b18.setPreferredSize(new java.awt.Dimension(60, 50));
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });
        jPanel1.add(b18);
        b18.setBounds(170, 200, 60, 50);

        bmul1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bmul1.setText("*");
        bmul1.setPreferredSize(new java.awt.Dimension(60, 50));
        bmul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmul1ActionPerformed(evt);
            }
        });
        jPanel1.add(bmul1);
        bmul1.setBounds(240, 200, 60, 50);

        bans1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bans1.setText("=");
        bans1.setPreferredSize(new java.awt.Dimension(60, 50));
        bans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bans1ActionPerformed(evt);
            }
        });
        jPanel1.add(bans1);
        bans1.setBounds(180, 320, 130, 40);

        bdot1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bdot1.setText(".");
        bdot1.setPreferredSize(new java.awt.Dimension(60, 50));
        bdot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdot1ActionPerformed(evt);
            }
        });
        jPanel1.add(bdot1);
        bdot1.setBounds(100, 260, 60, 50);

        bmod1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bmod1.setText("%");
        bmod1.setPreferredSize(new java.awt.Dimension(60, 50));
        bmod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmod1ActionPerformed(evt);
            }
        });
        jPanel1.add(bmod1);
        bmod1.setBounds(170, 260, 60, 50);

        b19.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b19.setText("0");
        b19.setPreferredSize(new java.awt.Dimension(60, 50));
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });
        jPanel1.add(b19);
        b19.setBounds(30, 260, 60, 50);

        bclear1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bclear1.setText("CE");
        bclear1.setPreferredSize(new java.awt.Dimension(60, 50));
        bclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclear1ActionPerformed(evt);
            }
        });
        jPanel1.add(bclear1);
        bclear1.setBounds(30, 320, 140, 40);

        jPanel4.setPreferredSize(new java.awt.Dimension(1250, 1110));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel4.setText("Total Amount");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(190, 100, 150, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel7.setText("Sub Total ");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(200, 20, 110, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel8.setText("Tax");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(210, 60, 90, 30);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jTextField11.setText("Rs 0.00");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField11);
        jTextField11.setBounds(480, 110, 310, 40);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jTextField12.setText("Rs 0.00");
        jPanel4.add(jTextField12);
        jTextField12.setBounds(480, 10, 310, 40);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jTextField13.setText("Rs 0.00");
        jPanel4.add(jTextField13);
        jTextField13.setBounds(480, 60, 310, 40);

        jButton1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(860, 70, 310, 50);

        jButton2.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(860, 10, 310, 50);

        jPanel2.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox1.setText("Burger");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(20, 260, 140, 53);

        jCheckBox2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox2.setText("Juices");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(20, 24, 140, 53);

        jCheckBox3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox3.setText("Pizza");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox3);
        jCheckBox3.setBounds(20, 80, 140, 53);

        jCheckBox4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox4.setText("Biryani");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox4);
        jCheckBox4.setBounds(20, 140, 140, 53);

        jCheckBox5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox5.setText("Pasta");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox5);
        jCheckBox5.setBounds(20, 200, 140, 53);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(170, 270, 100, 50);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(170, 20, 100, 50);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jPanel2.add(jTextField3);
        jTextField3.setBounds(170, 80, 100, 50);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jPanel2.add(jTextField4);
        jTextField4.setBounds(170, 150, 100, 50);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(170, 210, 100, 50);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 328));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 36)); // NOI18N
        jLabel1.setText("Total Cost of Items");

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 36)); // NOI18N
        jLabel2.setText("Total Delievery Cost ");

        jLabel3.setFont(new java.awt.Font("Calibri", 2, 36)); // NOI18N
        jLabel3.setText("Total Cost of Mileage");

        jLabel6.setFont(new java.awt.Font("Calibri", 2, 36)); // NOI18N
        jLabel6.setText("CGST");

        jLabel5.setFont(new java.awt.Font("Calibri", 2, 36)); // NOI18N
        jLabel5.setText("SGST");
        jLabel5.setToolTipText("");

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addComponent(jTextField9)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(278, 18, 680, 340);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ONLINE BILLING SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDisplay1ActionPerformed

    private void bdiv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdiv1ActionPerformed
        firstnum=Double.parseDouble(BDisplay1.getText());
        BDisplay1.setText("");
        operations = "/";
    }//GEN-LAST:event_bdiv1ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        String EnterNumber=BDisplay1.getText()+b10.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        String EnterNumber=BDisplay1.getText()+b11.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        String EnterNumber=BDisplay1.getText()+b12.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b12ActionPerformed

    private void badd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badd1ActionPerformed
        firstnum=Double.parseDouble(BDisplay1.getText());
        BDisplay1.setText("");
        operations = "+";
    }//GEN-LAST:event_badd1ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        String EnterNumber=BDisplay1.getText()+b13.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        String EnterNumber=BDisplay1.getText()+b14.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        String EnterNumber=BDisplay1.getText()+b15.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b15ActionPerformed

    private void bm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bm1ActionPerformed
        firstnum=Double.parseDouble(BDisplay1.getText());
        BDisplay1.setText("");
        operations = "-";
    }//GEN-LAST:event_bm1ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        String EnterNumber=BDisplay1.getText()+b16.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b16ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        String EnterNumber=BDisplay1.getText()+b17.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b17ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        String EnterNumber=BDisplay1.getText()+b18.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b18ActionPerformed

    private void bmul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmul1ActionPerformed
        firstnum=Double.parseDouble(BDisplay1.getText());
        BDisplay1.setText("");
        operations = "*";
    }//GEN-LAST:event_bmul1ActionPerformed

    private void bans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bans1ActionPerformed
        secondnum = Double.parseDouble(BDisplay1.getText());
        if(operations == "+"){
            result = firstnum + secondnum;
            answers =String.format("%.2f", result);
            BDisplay1.setText(answers);
        }
        else if(operations == "-"){
            result = firstnum - secondnum;
            answers =String.format("%.2f", result);
            BDisplay1.setText(answers);
        }
        else if(operations == "*"){
            result = firstnum * secondnum;
            answers =String.format("%.2f", result);
            BDisplay1.setText(answers);
        }
        else if(operations == "/"){
            result = firstnum / secondnum;
            answers =String.format("%.2f", result);
            BDisplay1.setText(answers);
        }
        else{
            result = firstnum % secondnum;
            answers =String.format("%.2f", result);
            BDisplay1.setText(answers);
        }
    }//GEN-LAST:event_bans1ActionPerformed

    private void bdot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdot1ActionPerformed
        if(!BDisplay1.getText().contains(".")){
            BDisplay1.setText(BDisplay1.getText()+bdot1.getText());

        }
    }//GEN-LAST:event_bdot1ActionPerformed

    private void bmod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmod1ActionPerformed
        firstnum=Double.parseDouble(BDisplay1.getText());
        BDisplay1.setText("");
        operations = "%";
    }//GEN-LAST:event_bmod1ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        String EnterNumber=BDisplay1.getText()+b19.getText();
        BDisplay1.setText(EnterNumber);
    }//GEN-LAST:event_b19ActionPerformed

    private void bclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclear1ActionPerformed
        BDisplay1.setText("");
    }//GEN-LAST:event_bclear1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   BDisplay1.setText("");
   jTextField1.setText("0");
    jTextField2.setText("0");
     jTextField3.setText("0");
    jTextField4.setText("0");
     jTextField5.setText("0");
      jTextField6.setText("0");
       jTextField7.setText("0");
        jTextField8.setText("0");
         jTextField9.setText("0");
          jTextField11.setText("Rs,0.00");
           jTextField10.setText("0");
            jTextField12.setText("Rs,0.00");
             jTextField13.setText("Rs,0.00");
             jCheckBox1.setSelected(false);
             jCheckBox2.setSelected(false);
             jCheckBox3.setSelected(false);
             jCheckBox4.setSelected(false);
             jCheckBox5.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed

    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
      if (jCheckBox2.isSelected()){
          jTextField2.setEditable(true);
           jTextField2.setText("");
           jTextField2.requestFocus();
          
      }
      else {
          jTextField2.setEditable(false);
          jTextField2.setText("0");
      }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
         if (jCheckBox3.isSelected()){
          jTextField3.setEditable(true);
           jTextField3.setText("");
           jTextField3.requestFocus();
          
      }
      else {
          jTextField3.setEditable(false);
          jTextField3.setText("0");
      }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
          if (jCheckBox4.isSelected()){
          jTextField4.setEditable(true);
           jTextField4.setText("");
           jTextField4.requestFocus();
          
      }
      else {
          jTextField4.setEditable(false);
          jTextField4.setText("0");
      }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
          if (jCheckBox5.isSelected()){
          jTextField5.setEditable(true);
           jTextField5.setText("");
           jTextField5.requestFocus();
          
      }
      else {
          jTextField5.setEditable(false);
          jTextField5.setText("0");
      }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         if (jCheckBox1.isSelected()){
          jTextField1.setEditable(true);
           jTextField1.setText("");
           jTextField1.requestFocus();
          
      }
      else {
          jTextField1.setEditable(false);
          jTextField1.setText("0");
      }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if((jCheckBox1.isSelected()) || (jCheckBox2.isSelected()) || (jCheckBox3.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()) || (jCheckBox1.isSelected())  ){
           double j= Double.parseDouble(jTextField2.getText())* 100;
           double p= Double.parseDouble(jTextField3.getText())* 500;
           double b= Double.parseDouble(jTextField4.getText())* 200;
           double p2= Double.parseDouble(jTextField5.getText())* 300;
           double b2= Double.parseDouble(jTextField1.getText())* 150;
           double total_items = j+p+b+p2+b2;
           double del = total_items/100;
           double mil = del*50/100;
           double subtotal = total_items + del + mil;
           double cgst = subtotal * 9/100;
           double sgst =cgst;
           double tax = cgst+sgst;
           double tamount = subtotal + tax;
           String item = String.format("%.2f",total_items);
           jTextField6.setText((String)item);
           String d = String.format("%.2f",del);
           jTextField7.setText((String)d);
           String m = String.format("%.2f",mil);
           jTextField8.setText((String)m);
           String s = String.format("%.2f",sgst);
           jTextField9.setText((String)s);
           String c = String.format("%.2f",cgst);
           jTextField10.setText((String)c);
           String sub = String.format("%.2f",subtotal);
           jTextField12.setText((String)sub);
           String t = String.format("%.2f",tax);
           jTextField13.setText((String)t);
           String TA = String.format("%.2f",tamount);
           jTextField11.setText((String)TA);
       }
       else{
           BDisplay1.setText("Please select items");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BDisplay1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton badd1;
    private javax.swing.JButton bans1;
    private javax.swing.JButton bclear1;
    private javax.swing.JButton bdiv1;
    private javax.swing.JButton bdot1;
    private javax.swing.JButton bm1;
    private javax.swing.JButton bmod1;
    private javax.swing.JButton bmul1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
